### PR TITLE
Add `module.exports.log` alias

### PR DESCRIPTION
**Pull request by demurgos**
Closes js-cli/fancy-log#14

### CODE REVIEW

**Comment by phated** [comment]
@demurgos I'm generally fine with this (though should we add a test?) but don't you think it'll make the gulplog transition more jarring.  If we changed everything to `.info` now, the gulplog change would just be a require change.

**Comment by demurgos** [comment]
I looked into adding a test but this change is more about the public interface of the package rather than its features. Duplicating the test for `fancyLog(...)` and replacing function calls to `fancyLog.log(...)`  did not fell adequate because this is not an alternative implementation but an alias. I also considered simply adding a test asserting that `fancyLog === fancyLog.log` but it seemed too simple to me (I can add it if you want).

I'm not sure if I understood well what you mean by "If we changed everything to `.info` now". Do you intend to discourage `.log` in favor of `.info` and update the dependent packages so they can later replace `fancy-log` by `gulplog` more easily (because it does not have a `.log` function)?
As mentioned in the issue, I still think that having `.log` as method has some value but if the long-term plan is to deprecate this library it may not be that important.

**Comment by phated** [comment]
This library won't be deprecated, but we'll need everyone to upgrade to gulplog in the future because gulp-cli uses it to properly support log levels.  The reason people can't upgrade right now is because gulplog usage causes blackholing of logs for people using the CLI that came shipped with 3.x - we've changed the messaging around installing gulp globally (using `npm install -g gulp-cli`) but people still have the old CLI in some cases.

**Comment by phated** [comment]
Actually, this might get deprecated when we get theming support in gulp-cli - it will likely not get used in the CLI after that.

**Comment by demurgos** [comment]
Ok, so "deprecating" might be too strong but the plan is to move away from this package.

I don't think that the argument that "you just need to change your require" will help much with the migration: you will still need to push the libraries to do the update. I mean: the hardest is to get an update, not the size of the update when the update is small anyway.

Regarding the `gulp-util` migration, I am still updating the list and reviewing the referenced PRs but I no longer have much time to push it to new libraries, and it seem similar for the other maintainers that helped with it. The long tail of plugins or private package will have to do the update itself. This main goal of this PR is to let people drop `gulp-util` without having to think about their changes (especially if they use stubs). You may be right that it may be better to incite them to better think about the kind of log (`.info`/ `.warn` / `.error`), but it's a different trade-off (better code but more work). Just close or merge the PR depending on what you think.

The best solution would be to immediately recommend `gulplog` instead of `fancy-log` and patch the cli in gulp 3 to support it. I guess that you already looked into it and concluded that it's not desirable.

**Comment by phated** [comment]
@demurgos Sorry that I've been hesitant on this.  I'm actually thinking that I don't want to land this because updating to `.info` and `.error` makes gulplog a drop-in replacement in the future.  I actually would prefer the default export to not be a log at all 😛 but I won't go that far.

The CLI that shipped with gulp@^3 is so far behind that it seems really scary to update it as though it were still supported.  We've already updated all our documentation to tell people to install gulp-cli directly.

Maybe gulp-cli could be updated to understand gulplog even on old gulp.  I've created an issue at https://github.com/gulpjs/gulp-cli/issues/152

**Pull request closed without merging**
